---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        files: \.(js|json|rb|md|py|sh|txt|yaml|yml)$
      - id: check-case-conflict
      - id: check-json
      - id: end-of-file-fixer
        exclude: "^(password_.*|src/test/resources/test)$"
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.1
    hooks:
      - id: yamllint
